---
title: To-do list
hero_image: images/banner.png
description: Code a to-do list web app to store important notes
theme: red
duration: 3
listed: false
ingredient: false
copyedit: true
curriculum: 0, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: animals, art, humour, space, photography, outdoors, music, games
technologies: electronic-components, sense-hat, html-css-javascript, scratch, python
site_areas: coderdojo
hardware: electronic-components, sense-hat
software: html-css-javascript, scratch, python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Get set up
- title: Add action to your buttons
- title: Add to-do items
  completion:
  - engaged
- title: Completing items
- title: Remove items
- title: Save the list
- title: Load a saved list
  completion:
  - internal
- title: 'Challenge: automatic saving'
